# Generated by Django 5.1.6 on 2025-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price_currency', models.CharField(max_length=5)),
                ('price_current', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('image_string', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
