# Generated by Django 4.2.19 on 2025-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_app', '0003_remove_user_clothing_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_clothing',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
