# Generated by Django 4.2.19 on 2025-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_app', '0004_user_clothing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_detail',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clothing_detail',
            name='composition',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_detail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_detail',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='clothing_detail',
            name='price_original',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clothing_detail',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clothing_detail',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clothing_detail',
            name='price_current',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_clothing',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
