# Generated by Django 5.1.6 on 2025-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_app', '0006_user_outfit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_id', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('brand', models.CharField(max_length=20)),
                ('image_url', models.URLField(null=True)),
            ],
        ),
    ]
